{
    "Service": "/appconsumos_qa_mb/Services/app_consumos_qa.service",
    "DefiningRequests": [{
            "Name": "Almacenes",
            "Query": "Almacenes"
        },
        {
            "Name": "AlmacenesApp",
            "Query": "AlmacenesApp"
        },
        {
            "Name": "Empleados",
            "Query": "Empleados"
        },
        {
            "Name": "EmpleadosApp",
            "Query": "EmpleadosApp"
        },
        {
            "Name": "Equipos",
            "Query": "Equipos"
        },
        {
            "Name": "Inventario",
            "Query": "Inventario"
        },
        {
            "Name": "MaterialesAlmacen",
            "Query": "MaterialesAlmacen"
        },
        {
            "Name": "Ordenes",
            "Query": "Ordenes"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/SyncFailureMessage.action",
    "OnSuccess": "/appconsumos_qa_mb/Rules/app_consumos_qa/ErrorArchive_CheckForSyncError.js"
}