{
	"_Type": "Action.Type.ProgressBanner",
	"OnFailure": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/OnlySyncFailureMessage.action",
	"OnSuccess": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/OnlyUploadOffline.action",
	"Message": "Sincronización en proceso...",
	"CompletionMessage": "Sincronización completada",
	"CompletionTimeout": 7
}