{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/UploadOffline.action",
    "OnFailure": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}