{
    "Service": "/appconsumos_qa_mb/Services/app_consumos_qa.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/DownloadStartedMessage.action",
    "OnFailure": "/appconsumos_qa_mb/Actions/app_consumos_qa/Service/SyncFailureMessage.action"
}