{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Create_AlmacenesApp"
	},
	"Target": {
		"Service": "/appconsumos_qa_mb/Services/app_consumos_qa.service",
		"EntitySet": "AlmacenesApp"
	},
	"Properties": {
		"sociedad": "",
		"almacen": "",
		"centro": "",
		"almacen_desc": "",
		"tipo": ""
	}
}