{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Create_Items_Planillas_Aceites"
	},
	"Target": {
		"Service": "/appconsumos_qa_mb/Services/app_consumos_qa.service",
		"EntitySet": "ItemPlanillasAceites"
	},
	"Properties": {
		"id": ""
	}
}