{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Create_EmpleadosApp"
	},
	"ShowActivityIndicator": true,
	"Target": {
		"Service": "/appconsumos_qa_mb/Services/app_consumos_qa.service",
		"EntitySet": "EmpleadosApp"
	},
	"Properties": {
		"ficha": "",
		"nombre": "",
		"correo": "",
		"rol": "",
		"cargo": "",
		"sociedad": ""
	}
}