{
	"_Type": "Action.Type.ODataService.Read",
	"ActionResult": {
		"_Name": "Read_ZBIW_MARDTSet"
	},
	"OnFailure": {
		"Name": "/appconsumos_qa_mb/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Error al intentar traer los datos de materiales - {#ActionResults:Read_ZBIW_MARDTSet/error}",
			"Title": "Error",
			"OKCaption": "Aceptar"
		}
	},
	"OnSuccess": "/appconsumos_qa_mb/Rules/Inventario/set_VisibleAgregarMaterialNuevo.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Cargando datos de materiales...",
	"Target": {
		"Service": "/appconsumos_qa_mb/Services/ZBODEGA_AGO_SRV.service",
		"EntitySet": "ZBIW_MARDTSet",
		"QueryOptions": "/appconsumos_qa_mb/Rules/Inventario/Get_FilterRead_ZBIW_MARDT.js"
	},
	"Properties": [
		"Matnr",
		"Txtmd"
	]
}