{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Update_Planilla_Aceite_Motor"
	},
	"OnFailure": {
		"Name": "/appconsumos_qa_mb/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Error: {#ActionResults:Update_Planilla_Aceite_Motor/error}",
			"Title": "Error",
			"OKCaption": "Ok"
		}
	},
	"OnSuccess": {
		"Name": "/appconsumos_qa_mb/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Se ha enviado la planilla correctamente",
			"Title": "Envío Exitoso",
			"OKCaption": "Aceptar",
			"OnOK": "/appconsumos_qa_mb/Rules/Aceites/Cerrar_Planilla_Aceite_Motor.js"
		}
	},
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Enviando Planilla Aceites...",
	"Target": {
		"Service": "/appconsumos_qa_mb/Services/app_consumos_qa.service",
		"EntitySet": "PlanillasAceites",
		"QueryOptions": "$filter=id eq {{#Page:Filtro_Aceites/#ClientData/data_planilla_motor/id}}"
	},
	"Properties": {
		"contador_fin": "/appconsumos_qa_mb/Rules/Aceites/get_contador_final_Motor.js",
		"estado": "Enviado",
		"total": "/appconsumos_qa_mb/Rules/Aceites/get_Total_Consumos_Motor.js"
	}
}