{
	"_Type": "Action.Type.ToastMessage",
	"Message": "Falló al cerrar el servicio de datos v2 - {#ActionResults:close/error}",
	"NumberOfLines": 1,
	"Duration": 3,
	"IsIconHidden": true,
	"Animated": true
}